---
- hosts: DCPOPSLINMRTG01

- package_facts:
    manager: auto
  name: Gather the package facts
  tags:
    - CCE-27275-7
    - CJIS-5.5.2
    - DISA-STIG-RHEL-07-040530
    - NIST-800-53-AC-9(1)
    - NIST-800-53-CM-6(a)
    - PCI-DSS-Req-10.2.4
    - configure_strategy
    - display_login_attempts
    - low_complexity
    - low_disruption
    - low_severity
    - no_reboot_needed

- name: Check if pam_lastlog.so is set
  lineinfile:
    path: /etc/pam.d/postlogin
    regexp: ^\s*(session)(\s+)[^\s]+(\s+)(pam_lastlog\.so)(\s+)(.*)
    state: absent
  check_mode: true
  changed_when: false
  register: pam_lastlog_exists
  when: '"pam" in ansible_facts.packages'
  tags:
    - CCE-27275-7
    - CJIS-5.5.2
    - DISA-STIG-RHEL-07-040530
    - NIST-800-53-AC-9(1)
    - NIST-800-53-CM-6(a)
    - PCI-DSS-Req-10.2.4
    - configure_strategy
    - display_login_attempts
    - low_complexity
    - low_disruption
    - low_severity
    - no_reboot_needed

- name: Make sure pam_lastlog.so control is required
  replace:
    path: /etc/pam.d/postlogin
    regexp: ^\s*(session)(\s+)[^\s]+(\s+)(pam_lastlog\.so)(\s+)(.*)
    replace: \1\2required\3\4\5\6
  register: control_update_result
  when: '"pam" in ansible_facts.packages'
  tags:
    - CCE-27275-7
    - CJIS-5.5.2
    - DISA-STIG-RHEL-07-040530
    - NIST-800-53-AC-9(1)
    - NIST-800-53-CM-6(a)
    - PCI-DSS-Req-10.2.4
    - configure_strategy
    - display_login_attempts
    - low_complexity
    - low_disruption
    - low_severity
    - no_reboot_needed

- name: Add control for pam_lastlog.so module
  lineinfile:
    path: /etc/pam.d/postlogin
    line: session required pam_lastlog.so showfailed
  when:
    - '"pam" in ansible_facts.packages'
    - not pam_lastlog_exists.found
  register: add_new_pam_lastlog_control_result
  tags:
    - CCE-27275-7
    - CJIS-5.5.2
    - DISA-STIG-RHEL-07-040530
    - NIST-800-53-AC-9(1)
    - NIST-800-53-CM-6(a)
    - PCI-DSS-Req-10.2.4
    - configure_strategy
    - display_login_attempts
    - low_complexity
    - low_disruption
    - low_severity
    - no_reboot_needed

- name: Add 'showfailed' arg to pam_lastlog.so module
  pamd:
    name: postlogin
    type: session
    control: required
    module_path: pam_lastlog.so
    module_arguments: showfailed
    state: args_present
  when:
    - '"pam" in ansible_facts.packages'
    - not add_new_pam_lastlog_control_result.changed
  tags:
    - CCE-27275-7
    - CJIS-5.5.2
    - DISA-STIG-RHEL-07-040530
    - NIST-800-53-AC-9(1)
    - NIST-800-53-CM-6(a)
    - PCI-DSS-Req-10.2.4
    - configure_strategy
    - display_login_attempts
    - low_complexity
    - low_disruption
    - low_severity
    - no_reboot_needed

- name: Remove 'silent' arg for pam_lastlog.so module
  pamd:
    name: postlogin
    type: session
    control: required
    module_path: pam_lastlog.so
    module_arguments: silent
    state: args_absent
  when:
    - '"pam" in ansible_facts.packages'
    - not add_new_pam_lastlog_control_result.changed
  tags:
    - CCE-27275-7
    - CJIS-5.5.2
    - DISA-STIG-RHEL-07-040530
    - NIST-800-53-AC-9(1)
    - NIST-800-53-CM-6(a)
    - PCI-DSS-Req-10.2.4
    - configure_strategy
    - display_login_attempts
    - low_complexity
    - low_disruption
    - low_severity
    - no_reboot_needed
