---
- hosts: DCPORAREPOSRV01
  tasks:
    - name: Accepting Splunk license
      shell: /opt/splunkforwarder/bin/splunk enable boot-start --answer-yes -user splunk --accept-license

    - name: connect to splunk indexer server
      shell: /opt/splunkforwarder/bin/splunk add forward-server splk-index1.secedu.qa:9997 -auth t-o.sawant-admin@education.qa:aUhgSpSv

    - name: connect to splunk indexer server
      shell: /opt/splunkforwarder/bin/splunk add forward-server splk-index2.secedu.qa:9997 -auth t-o.sawant-admin@education.qa:aUhgSpSv

    - name: connect to splunk indexer server
      shell: /opt/splunkforwarder/bin/splunk add forward-server splk-index3.secedu.qa:9997 -auth t-o.sawant-admin@education.qa:aUhgSpSv

    - name: path which need to be monitored
      shell: /opt/splunkforwarder/bin/splunk add monitor /var/log/ -index main -sourcetype %ALL%

    - name: splunk service final restart
      shell: /opt/splunkforwarder/bin/splunk restart
