---
- hosts: templates
  tasks:
    - name: copying VMware-Log-Insight-Agent rpm file from DCPOPSAUTOVM01 to target machines
      copy:
        src: files/VMware-Log-Insight-Agent-4.8.0-13020979.noarch_10.200.130.81.rpm
        dest: /tmp/
        owner: root
        group: root
        mode: 0644

    - name: install VMware-Log-Insight-Agent package on the servers
      yum:
        name: /tmp/VMware-Log-Insight-Agent-4.8.0-13020979.noarch_10.200.130.81.rpm
        state: present
