---

- name: Add {{ os_group }} group
  group:
    name: "{{ os_group }}"
    state: present  
  become: yes  

- name: Add {{ os_user }} user
  user:
    name: "{{ os_user }}"
    group: "{{ os_group }}"
    home: /home/{{ os_user }}
    shell: /bin/bash
    comment: Splunk User
  become: yes

- name: Create {{ splunk_uf_home }} dir
  file:
    path: "{{ splunk_uf_home }}"
    state: directory
    mode: 0755  
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
  become: yes

- name: copying SPLUNK_FORWARDER rpm file from DCPOPSAUTOVM01 to target machines
  copy:
    src: /etc/ansible/task-list/files/splunkforwarder-8.0.0-1357bef0a7f6-Linux-x86_64.tgz
    dest: /home/{{ os_user }}/splunkforwarder-8.0.0-1357bef0a7f6-Linux-x86_64.tgz
    owner: splunk
    group: splunk
    mode: 0644

- name: -TGZ- Extract {{ splunk_uf_tgz }} to {{ splunk_uf_home }} to install
  unarchive:
    src: /home/{{ os_user }}/{{ splunk_uf_tgz }}
    dest: "{{ splunk_uf_home }}/.."
    remote_src: yes
    owner: "{{ os_user }}"
    group: "{{ os_group }}"    
  become: yes

- name: Create user-seed.conf file for default admin creds
  template:
    src: user-seed.conf.j2
    dest: "{{ splunk_uf_home }}/etc/system/local/user-seed.conf"
  become: yes

- name: Set {{ splunk_uf_home }} owner & group recursively
  file:
    path: "{{ splunk_uf_home }}"
    state: directory
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
    recurse: yes
  become: yes  


- name: -initd- Splunk enable boot-start
  command: "{{ splunk_uf_home }}/bin/splunk enable boot-start -user {{ os_user }} --no-prompt --answer-yes --accept-license"
  become: yes 

- name: -initd- Start Splunk UF for the first time
  command: "{{ splunk_uf_home }}/bin/splunk start --no-prompt --answer-yes --accept-license"
  become: yes    

  
- name: "Create symlink to splunk in /usr/local/bin"
  file:
    src: "{{ splunk_uf_home }}/bin/splunk"
    path: /usr/local/bin/splunk
    state: link
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
  become: yes
